# Generated by Django 4.2 on 2023-04-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('website', models.URLField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Movie', 'Movie'), ('WebSeries', 'WebSeries'), ('Podcast', 'Podcast'), ('Documentary', 'Documentary')], default='Movie', max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Non-fiction', 'Non-fiction'), ('Comedy', 'Comedy'), ('RomCom', 'RomCom'), ('Drama', 'Drama')], default='Non-Fiction', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist.streamplatform')),
            ],
        ),
    ]
