# Generated by Django 4.2 on 2023-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
