# Generated by Django 4.2 on 2023-04-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='watchlist', to='watchlist.streamplatform'),
        ),
    ]
